"""Initial database setup with all models and naming convention

Revision ID: 3b6841a5c112
Revises: 
Create Date: 2025-04-22 22:54:11.530740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b6841a5c112'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('member',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_member'))
    )
    with op.batch_alter_table('member', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_member_name'), ['name'], unique=False)

    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('logo_filename', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project'))
    )
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_name'), ['name'], unique=False)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user'))
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('ata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('time', sa.Time(), nullable=True),
    sa.Column('format', sa.String(length=50), nullable=False),
    sa.Column('location_or_platform', sa.String(length=200), nullable=True),
    sa.Column('discussion_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], name=op.f('fk_ata_project_id_project'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ata'))
    )
    with op.batch_alter_table('ata', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ata_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_ata_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_ata_project_id'), ['project_id'], unique=False)

    op.create_table('project_members',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['member.id'], name=op.f('fk_project_members_member_id_member'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], name=op.f('fk_project_members_project_id_project'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id', 'member_id', name=op.f('pk_project_members'))
    )
    op.create_table('ata_attendee',
    sa.Column('ata_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('is_present', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['ata_id'], ['ata.id'], name=op.f('fk_ata_attendee_ata_id_ata'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['member_id'], ['member.id'], name=op.f('fk_ata_attendee_member_id_member'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ata_id', 'member_id', name=op.f('pk_ata_attendee'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ata_attendee')
    op.drop_table('project_members')
    with op.batch_alter_table('ata', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ata_project_id'))
        batch_op.drop_index(batch_op.f('ix_ata_date'))
        batch_op.drop_index(batch_op.f('ix_ata_created_at'))

    op.drop_table('ata')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))

    op.drop_table('user')
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_name'))

    op.drop_table('project')
    with op.batch_alter_table('member', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_member_name'))

    op.drop_table('member')
    # ### end Alembic commands ###
