"""Make location_type and details in Ata model nullable

Revision ID: 7c8e04ffc4c1
Revises: 972209487695
Create Date: 2025-06-20 13:42:15.552494

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7c8e04ffc4c1'
down_revision = '972209487695'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ata', schema=None) as batch_op:
        batch_op.alter_column('location_type',
               existing_type=postgresql.ENUM('presencial', 'online', 'hibrido', name='location_type_enum'),
               nullable=True)
        batch_op.drop_index(batch_op.f('ix_ata_meeting_datetime'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ata', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ata_meeting_datetime'), ['meeting_datetime'], unique=False)
        batch_op.alter_column('location_type',
               existing_type=postgresql.ENUM('presencial', 'online', 'hibrido', name='location_type_enum'),
               nullable=False)

    # ### end Alembic commands ###