"""Add is_active flag to Member for soft delete

Revision ID: a844b4dc362d
Revises: b0c8fbb83aba
Create Date: 2025-04-25 00:48:52.083604

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a844b4dc362d'
down_revision = 'b0c8fbb83aba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. Adiciona a coluna PERMITINDO nulos temporariamente
    #    (Mesmo que o modelo diga nullable=False, Alembic precisa fazer isso em 2 passos)
    op.add_column('member', sa.Column('is_active', sa.Boolean(), nullable=True))

    # 2. Preenche a nova coluna com o valor padrão (True) para as linhas existentes
    #    Isso garante que não haverá nulos antes de adicionar a restrição NOT NULL
    op.execute("UPDATE member SET is_active = 1") # Use 1 para True em SQLite

    # 3. Altera a coluna para NÃO permitir nulos
    with op.batch_alter_table('member', schema=None) as batch_op:
        # A forma de alterar nullable pode variar ligeiramente dependendo da versão do Alembic/SQLAlchemy
        # Tente uma destas, a primeira é a mais comum:
        try:
            batch_op.alter_column('is_active', existing_type=sa.Boolean(), nullable=False)
        except Exception:
            # Alternativa se a acima não funcionar (menos comum)
            batch_op.alter_column('is_active', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('member', 'is_active')

    # ### end Alembic commands ###
